title: "GMS's Blog"
description: "코딩하는 사회학자"
url: "https://gms80175064.github.io/"
baseurl: "https://gms80175064.github.io/"
name: "숨겨진 정보들을 찾아보자!"

theme: null

# debug:
#   compress: true
#   dist: false
#   shortcodes: true

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
